"""Seed canonical DD checklist templates into the database.

Run once after the migration:
    cd apps/api && poetry run python -c "
    import asyncio
    from app.core.database import async_session_factory
    from app.modules.due_diligence.seed_templates import seed_dd_templates

    async def main():
        async with async_session_factory() as db:
            await seed_dd_templates(db)

    asyncio.run(main())
    "
"""

from __future__ import annotations

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.due_diligence import DDChecklistItem, DDChecklistTemplate

logger = structlog.get_logger()

# ── Template definitions ──────────────────────────────────────────────────────
# Each entry: (asset_type, deal_stage, jurisdiction_group, name, description, items)
# items: list of dicts with keys:
#   category, name, description, requirement_type, required_document_types,
#   verification_criteria, priority, sort_order, estimated_time_hours, regulatory_reference

TEMPLATES: list[dict] = [

    # ── Solar / full_dd / EU ─────────────────────────────────────────────────
    {
        "asset_type": "solar",
        "deal_stage": "full_dd",
        "jurisdiction_group": "EU",
        "name": "Solar PV — Full Due Diligence (EU)",
        "description": "Comprehensive due diligence checklist for utility-scale solar PV projects in the European Union.",
        "items": [
            # Legal
            {
                "category": "legal",
                "name": "Land title / lease agreement",
                "description": "Confirm clear title or long-term lease (≥ project lifetime + 5 years) for the project site.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Lease or title deed confirming unencumbered rights for project term, signed by authorised parties.",
                "priority": "required",
                "sort_order": 10,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Corporate structure & ownership",
                "description": "Confirm SPV ownership chain, UBOs, and absence of sanctioned parties.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Company register extracts, shareholder register, UBO declaration, sanctions screening result.",
                "priority": "required",
                "sort_order": 20,
                "estimated_time_hours": 3.0,
                "regulatory_reference": "EU AML 6AMLD",
            },
            {
                "category": "legal",
                "name": "EPC / construction contract",
                "description": "Review EPC contract: scope, liquidated damages, performance warranties, retention.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Fixed-price lump-sum EPC with LD clause ≥ 10% contract value, performance warranty ≥ 2 years.",
                "priority": "required",
                "sort_order": 30,
                "estimated_time_hours": 8.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "O&M agreement",
                "description": "Review operations & maintenance contract terms, SLAs, and termination rights.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Long-term O&M contract (≥5 years) with availability guarantee ≥98%.",
                "priority": "required",
                "sort_order": 40,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Power Purchase Agreement (PPA)",
                "description": "Confirm PPA tenor, offtake counterparty creditworthiness, price escalation mechanism.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "PPA ≥15 years, investment-grade offtaker or sovereign-backed, price floor defined.",
                "priority": "required",
                "sort_order": 50,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            # Financial
            {
                "category": "financial",
                "name": "Financial model (base + stress cases)",
                "description": "Independent review of financial model: assumptions, IRR, DSCR, sensitivity analysis.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "DSCR ≥1.20x in base case; P90 IRR ≥8% equity. Model audited by independent engineer.",
                "priority": "required",
                "sort_order": 60,
                "estimated_time_hours": 16.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "3-year audited financial statements",
                "description": "Audited accounts of the project sponsor/developer for last 3 fiscal years.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "Signed audit opinions, no going-concern qualifications.",
                "priority": "required",
                "sort_order": 70,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "Construction cost breakdown",
                "description": "Detailed CAPEX schedule and contingency provisions.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "Contingency ≥5% of CAPEX; cost estimates from independent quantity surveyor.",
                "priority": "required",
                "sort_order": 80,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            # Technical
            {
                "category": "technical",
                "name": "Solar resource / yield assessment (P50/P90)",
                "description": "Independent energy yield assessment using ≥10 years irradiance data.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "P50/P90 yield report from accredited firm; data sources: Solargis or equivalent.",
                "priority": "required",
                "sort_order": 90,
                "estimated_time_hours": 8.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Grid connection / interconnection agreement",
                "description": "Signed grid connection agreement and queue position confirmation.",
                "requirement_type": "document_review",
                "required_document_types": ["permit"],
                "verification_criteria": "Executed connection agreement with TSO/DSO; connection capacity confirmed.",
                "priority": "required",
                "sort_order": 100,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Module & inverter technical specifications",
                "description": "Bankable equipment: tier-1 module manufacturer, inverter warranty terms.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "Tier-1 modules (Bloomberg NEF list); inverter manufacturer in top 10 globally; 25-year power warranty.",
                "priority": "required",
                "sort_order": 110,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Site survey and geotechnical report",
                "description": "Foundation design suitability, soil conditions, flood risk.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "Geotechnical report stamped by chartered engineer; no unexploded ordnance risk.",
                "priority": "required",
                "sort_order": 120,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            # Environmental
            {
                "category": "environmental",
                "name": "Environmental Impact Assessment (EIA)",
                "description": "Statutory EIA approved by competent authority.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "EIA approval letter from competent authority; no outstanding objections.",
                "priority": "required",
                "sort_order": 130,
                "estimated_time_hours": 6.0,
                "regulatory_reference": "EU EIA Directive 2011/92/EU",
            },
            {
                "category": "environmental",
                "name": "Biodiversity and habitat assessment",
                "description": "Natura 2000 screening; protected species survey.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "Appropriate assessment completed; no significant adverse effects on Natura 2000 sites.",
                "priority": "required",
                "sort_order": 140,
                "estimated_time_hours": 4.0,
                "regulatory_reference": "EU Habitats Directive 92/43/EEC",
            },
            {
                "category": "environmental",
                "name": "EU Taxonomy alignment assessment",
                "description": "Do No Significant Harm (DNSH) assessment against 6 environmental objectives.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "Technical screening criteria met for climate change mitigation; DNSH for all 6 objectives documented.",
                "priority": "required",
                "sort_order": 150,
                "estimated_time_hours": 8.0,
                "regulatory_reference": "EU Taxonomy Regulation 2020/852",
            },
            # Regulatory
            {
                "category": "regulatory",
                "name": "Construction permit / planning consent",
                "description": "Final building permit issued with no conditions outstanding.",
                "requirement_type": "document_review",
                "required_document_types": ["permit"],
                "verification_criteria": "Permit with expiry date ≥ construction completion + 6 months; no appeals pending.",
                "priority": "required",
                "sort_order": 160,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "regulatory",
                "name": "Feed-in tariff / subsidy agreement",
                "description": "Government subsidy award letter or CfD agreement.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Subsidy awarded and legally binding; change-of-law provision included.",
                "priority": "recommended",
                "sort_order": 170,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            {
                "category": "regulatory",
                "name": "Grid code compliance certificate",
                "description": "Confirmation that the plant design meets grid code requirements.",
                "requirement_type": "document_review",
                "required_document_types": ["permit"],
                "verification_criteria": "Compliance letter from TSO/DSO or independent engineer statement.",
                "priority": "required",
                "sort_order": 180,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            # Insurance
            {
                "category": "insurance",
                "name": "Construction All Risks (CAR) insurance",
                "description": "CAR policy covering 100% of construction value.",
                "requirement_type": "document_review",
                "required_document_types": ["insurance"],
                "verification_criteria": "CAR policy with insured value = contract price; project lender named as additional insured.",
                "priority": "required",
                "sort_order": 190,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "insurance",
                "name": "Operational insurance package",
                "description": "Property damage, business interruption, and third-party liability.",
                "requirement_type": "document_review",
                "required_document_types": ["insurance"],
                "verification_criteria": "Combined cover ≥ replacement value; BI cover ≥ 12 months gross revenue.",
                "priority": "required",
                "sort_order": 200,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "insurance",
                "name": "Weather/irradiance index insurance",
                "description": "Optional parametric insurance product for below-P90 yield events.",
                "requirement_type": "information",
                "required_document_types": ["insurance"],
                "verification_criteria": "Term sheet reviewed; trigger and payout structure verified.",
                "priority": "optional",
                "sort_order": 210,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
        ],
    },

    # ── Wind / full_dd / EU ──────────────────────────────────────────────────
    {
        "asset_type": "wind",
        "deal_stage": "full_dd",
        "jurisdiction_group": "EU",
        "name": "Onshore Wind — Full Due Diligence (EU)",
        "description": "Comprehensive due diligence checklist for onshore wind projects in the European Union.",
        "items": [
            # Legal
            {
                "category": "legal",
                "name": "Land lease / easement agreements",
                "description": "Long-term site access agreements for all turbine positions and access roads.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Lease term ≥ project life + 5 years; decommissioning bond provisions included.",
                "priority": "required",
                "sort_order": 10,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Corporate structure & ownership",
                "description": "SPV structure, UBOs, sanctions screening.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Company register extracts, UBO declaration, sanctions screening passed.",
                "priority": "required",
                "sort_order": 20,
                "estimated_time_hours": 3.0,
                "regulatory_reference": "EU AML 6AMLD",
            },
            {
                "category": "legal",
                "name": "Turbine Supply Agreement (TSA)",
                "description": "Turbine supply contract with full-service warranty terms.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Bankable OEM; 5-year full-service warranty minimum; availability guarantee ≥97%.",
                "priority": "required",
                "sort_order": 30,
                "estimated_time_hours": 8.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "EPC / BOP contract",
                "description": "Balance-of-plant contract covering civil works, roads, substation.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Fixed-price BOP contract with LD clause; milestone-based payment schedule.",
                "priority": "required",
                "sort_order": 40,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Long-term service agreement (LTSA)",
                "description": "OEM or third-party LTSA covering major maintenance.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "LTSA ≥10 years; availability guarantee ≥97%; spare parts commitment.",
                "priority": "required",
                "sort_order": 50,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "PPA / offtake agreement",
                "description": "Long-term power purchase agreement with creditworthy offtaker.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "PPA ≥12 years; investment-grade or government-backed counterparty.",
                "priority": "required",
                "sort_order": 60,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            # Financial
            {
                "category": "financial",
                "name": "Financial model (base + stress)",
                "description": "Wind-specific financial model with P50/P90 revenue scenarios.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "P90 DSCR ≥1.15x; equity IRR ≥9% base; model independently audited.",
                "priority": "required",
                "sort_order": 70,
                "estimated_time_hours": 16.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "3-year audited financial statements",
                "description": "Sponsor audited accounts.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "Clean audit opinions for 3 consecutive years.",
                "priority": "required",
                "sort_order": 80,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "CAPEX and OPEX cost breakdown",
                "description": "Detailed construction and operational cost schedule.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "Independent cost review; OPEX benchmarked against comparable wind farms.",
                "priority": "required",
                "sort_order": 90,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            # Technical
            {
                "category": "technical",
                "name": "Wind resource assessment (P50/P90)",
                "description": "Independent wind study using ≥10 years reanalysis + on-site mast data.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "Report from accredited firm (e.g. DNV, Garrad Hassan); uncertainty analysis included.",
                "priority": "required",
                "sort_order": 100,
                "estimated_time_hours": 10.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Wake effect study",
                "description": "Turbine array losses due to wake interactions.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "Wake losses quantified in P50 yield; CFD or validated model used.",
                "priority": "required",
                "sort_order": 110,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Tower and foundation design review",
                "description": "Structural design for tower, foundation, and substation buildings.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "Structural calculations stamped by chartered engineer; fatigue life ≥20 years.",
                "priority": "required",
                "sort_order": 120,
                "estimated_time_hours": 8.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Grid connection / interconnection agreement",
                "description": "Executed grid connection agreement.",
                "requirement_type": "document_review",
                "required_document_types": ["permit"],
                "verification_criteria": "Signed agreement; transmission capacity confirmed for full installed capacity.",
                "priority": "required",
                "sort_order": 130,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            # Environmental
            {
                "category": "environmental",
                "name": "Environmental Impact Assessment (EIA)",
                "description": "Full statutory EIA with approval from competent authority.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "EIA approved; no outstanding conditions or appeals.",
                "priority": "required",
                "sort_order": 140,
                "estimated_time_hours": 6.0,
                "regulatory_reference": "EU EIA Directive 2011/92/EU",
            },
            {
                "category": "environmental",
                "name": "Noise impact assessment",
                "description": "Cumulative noise levels at nearest noise-sensitive receptors.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "Noise levels comply with national limits; shadow flicker < 30h/year per receptor.",
                "priority": "required",
                "sort_order": 150,
                "estimated_time_hours": 4.0,
                "regulatory_reference": "ISO 9613-2",
            },
            {
                "category": "environmental",
                "name": "Bird and bat impact study",
                "description": "Flight line surveys, collision risk modelling for raptors and bats.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "Collision risk model accepted by competent authority; mitigation measures defined.",
                "priority": "required",
                "sort_order": 160,
                "estimated_time_hours": 6.0,
                "regulatory_reference": "EU Birds Directive 2009/147/EC",
            },
            {
                "category": "environmental",
                "name": "EU Taxonomy alignment (DNSH)",
                "description": "DNSH assessment for wind against all 6 EU Taxonomy objectives.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "Climate mitigation technical criteria met; all DNSH checks documented.",
                "priority": "required",
                "sort_order": 170,
                "estimated_time_hours": 6.0,
                "regulatory_reference": "EU Taxonomy Regulation 2020/852",
            },
            # Regulatory
            {
                "category": "regulatory",
                "name": "Planning / construction permits",
                "description": "All permits required for construction.",
                "requirement_type": "document_review",
                "required_document_types": ["permit"],
                "verification_criteria": "All permits in place; no outstanding conditions; permit conditions checked against design.",
                "priority": "required",
                "sort_order": 180,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            {
                "category": "regulatory",
                "name": "Subsidy / CfD contract",
                "description": "Government subsidy award.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Subsidy contract executed and unconditional.",
                "priority": "recommended",
                "sort_order": 190,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            # Insurance
            {
                "category": "insurance",
                "name": "Construction All Risks insurance",
                "description": "CAR policy for full construction value.",
                "requirement_type": "document_review",
                "required_document_types": ["insurance"],
                "verification_criteria": "CAR insured value = contract price; lender named as additional insured.",
                "priority": "required",
                "sort_order": 200,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "insurance",
                "name": "Operational insurance package",
                "description": "Property all risks, machinery breakdown, BI, third-party liability.",
                "requirement_type": "document_review",
                "required_document_types": ["insurance"],
                "verification_criteria": "Cover ≥ replacement value; BI ≥ 18 months revenue for wind.",
                "priority": "required",
                "sort_order": 210,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "insurance",
                "name": "Decommissioning security",
                "description": "Financial security for end-of-life decommissioning obligations.",
                "requirement_type": "information",
                "required_document_types": ["insurance"],
                "verification_criteria": "Decommissioning cost estimate; bond or escrow mechanism confirmed.",
                "priority": "recommended",
                "sort_order": 220,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
        ],
    },

    # ── Real Estate / full_dd / global ───────────────────────────────────────
    {
        "asset_type": "real_estate",
        "deal_stage": "full_dd",
        "jurisdiction_group": None,
        "name": "Real Estate — Full Due Diligence (Global)",
        "description": "Comprehensive due diligence checklist for commercial real estate acquisitions.",
        "items": [
            # Legal
            {
                "category": "legal",
                "name": "Title search and title insurance",
                "description": "Full title investigation confirming clean legal title to the property.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Title search clean; title insurance policy in place at acquisition.",
                "priority": "required",
                "sort_order": 10,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Survey / boundary review",
                "description": "ALTA/ACSM or equivalent land survey.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "Survey confirms boundaries; no encroachments or easement conflicts.",
                "priority": "required",
                "sort_order": 20,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Lease review — all existing tenants",
                "description": "Review all lease abstracts: rent, term, options, break clauses, repairing obligations.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "All leases reviewed; rent roll reconciled; no undisclosed side letters.",
                "priority": "required",
                "sort_order": 30,
                "estimated_time_hours": 10.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Purchase and sale agreement review",
                "description": "PSA terms, reps & warranties, indemnification provisions.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Satisfactory reps and warranties; adequate indemnity provisions; clear CP conditions.",
                "priority": "required",
                "sort_order": 40,
                "estimated_time_hours": 8.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Corporate / ownership structure",
                "description": "SPV structure, ownership chain, existing debt/liens.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Clean ownership; no undisclosed liens or encumbrances on the asset.",
                "priority": "required",
                "sort_order": 50,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            # Financial
            {
                "category": "financial",
                "name": "Rent roll — current and historical",
                "description": "Detailed rent roll with occupancy, lease expiry, rent review dates.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "Rent roll reconciled against leases; WAULT ≥3 years for core assets.",
                "priority": "required",
                "sort_order": 60,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "3-year historical property financials",
                "description": "P&L, NOI, operating expense breakdown for last 3 years.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "NOI reconciled; operating expenses benchmarked; no material one-offs unexplained.",
                "priority": "required",
                "sort_order": 70,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "Independent valuation / appraisal",
                "description": "RICS or MAI appraisal at acquisition.",
                "requirement_type": "document_review",
                "required_document_types": ["valuation"],
                "verification_criteria": "Red-book appraisal within 6 months; appraiser is RICS/MAI; cap rate methodology documented.",
                "priority": "required",
                "sort_order": 80,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "CAPEX reserve analysis",
                "description": "5-year CAPEX reserve forecast based on PCA findings.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "CAPEX reserve ≥ immediate needs + 10% contingency; PCA-backed.",
                "priority": "required",
                "sort_order": 90,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            # Technical
            {
                "category": "technical",
                "name": "Property Condition Assessment (PCA)",
                "description": "Full ASTM E2018 PCA by independent engineer.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "PCA completed; immediate needs < 1% of acquisition cost; 10-year capex schedule provided.",
                "priority": "required",
                "sort_order": 100,
                "estimated_time_hours": 8.0,
                "regulatory_reference": "ASTM E2018",
            },
            {
                "category": "technical",
                "name": "Building systems inspection",
                "description": "MEP, roof, structure, facade assessment.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "Key systems inspected; age and condition documented; remaining useful life ≥10 years for critical systems.",
                "priority": "required",
                "sort_order": 110,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            # Environmental
            {
                "category": "environmental",
                "name": "Phase I Environmental Site Assessment",
                "description": "ASTM E1527 Phase I ESA by qualified environmental professional.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "Phase I within 12 months; no Recognized Environmental Conditions (RECs) or RECs addressed.",
                "priority": "required",
                "sort_order": 120,
                "estimated_time_hours": 4.0,
                "regulatory_reference": "ASTM E1527",
            },
            {
                "category": "environmental",
                "name": "Phase II ESA (if RECs identified)",
                "description": "Soil and groundwater sampling to characterise contamination.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "Phase II results below applicable cleanup standards; remediation plan if required.",
                "priority": "recommended",
                "sort_order": 130,
                "estimated_time_hours": 8.0,
                "regulatory_reference": "ASTM E1903",
            },
            {
                "category": "environmental",
                "name": "Asbestos / lead / mold survey",
                "description": "Hazardous materials inspection for buildings pre-1990.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "O&M plan in place for ACM; no immediate remediation required or budgeted.",
                "priority": "required",
                "sort_order": 140,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            # Regulatory
            {
                "category": "regulatory",
                "name": "Zoning and land-use compliance",
                "description": "Confirm current use is permitted; check any non-conforming use status.",
                "requirement_type": "document_review",
                "required_document_types": ["permit"],
                "verification_criteria": "Zoning confirmed; current use is by-right; no pending rezoning that adversely affects value.",
                "priority": "required",
                "sort_order": 150,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "regulatory",
                "name": "Certificates of occupancy",
                "description": "CO on file for all uses; temporary COs resolved.",
                "requirement_type": "document_review",
                "required_document_types": ["permit"],
                "verification_criteria": "CO for all floors/uses; no open building violations.",
                "priority": "required",
                "sort_order": 160,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "regulatory",
                "name": "ADA / building code compliance",
                "description": "Accessibility compliance review.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "No material ADA deficiencies; open building code violations resolved or budgeted.",
                "priority": "required",
                "sort_order": 170,
                "estimated_time_hours": 3.0,
                "regulatory_reference": "ADA 1990 / local building codes",
            },
            # Insurance
            {
                "category": "insurance",
                "name": "Property and casualty insurance review",
                "description": "Review existing policies; confirm adequate replacement cost coverage.",
                "requirement_type": "document_review",
                "required_document_types": ["insurance"],
                "verification_criteria": "Coverage ≥ replacement cost; lender requirements met; no major exclusions.",
                "priority": "required",
                "sort_order": 180,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "insurance",
                "name": "Rent loss / business interruption insurance",
                "description": "BI/rent loss coverage for 12 months minimum.",
                "requirement_type": "document_review",
                "required_document_types": ["insurance"],
                "verification_criteria": "BI cover ≥ 12 months NOI; waiting period ≤ 72 hours.",
                "priority": "required",
                "sort_order": 190,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "insurance",
                "name": "Flood and earthquake zone assessment",
                "description": "FEMA flood zone determination; seismic zone risk.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "Flood zone determination; flood insurance in place if zone A/V; seismic risk quantified.",
                "priority": "recommended",
                "sort_order": 200,
                "estimated_time_hours": 2.0,
                "regulatory_reference": "FEMA FIRM",
            },
        ],
    },

    # ── Private Credit / full_dd / global ────────────────────────────────────
    {
        "asset_type": "private_credit",
        "deal_stage": "full_dd",
        "jurisdiction_group": None,
        "name": "Private Credit — Full Due Diligence (Global)",
        "description": "Comprehensive due diligence checklist for direct lending and private credit transactions.",
        "items": [
            # Legal
            {
                "category": "legal",
                "name": "Credit agreement review",
                "description": "Full review of credit agreement, facility terms, negative covenants, events of default.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Credit agreement executed; all conditions precedent satisfied; material covenants identified.",
                "priority": "required",
                "sort_order": 10,
                "estimated_time_hours": 16.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Security package and perfection",
                "description": "First-ranking security over key assets; UCC filings or local equivalent.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Security perfected in all relevant jurisdictions; priority confirmed by legal opinion.",
                "priority": "required",
                "sort_order": 20,
                "estimated_time_hours": 8.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Intercreditor agreement",
                "description": "If syndicated or layered capital: intercreditor agreement review.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Waterfall confirmed; enforcement rights preserved; no pari-passu ambiguity.",
                "priority": "required",
                "sort_order": 30,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Corporate structure and borrower entity",
                "description": "Corporate chart, jurisdiction, authorised signatories, UBO.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Borrower duly authorised; no undisclosed side agreements; UBO checked.",
                "priority": "required",
                "sort_order": 40,
                "estimated_time_hours": 4.0,
                "regulatory_reference": "EU AML 6AMLD",
            },
            {
                "category": "legal",
                "name": "Legal opinions (enforceability, security)",
                "description": "Local counsel opinions on enforceability and security perfection.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Clean legal opinions in all relevant jurisdictions; no material qualifications.",
                "priority": "required",
                "sort_order": 50,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            # Financial
            {
                "category": "financial",
                "name": "3-year audited financial statements",
                "description": "Audited P&L, balance sheet, cash flow for borrower.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "3 consecutive years audited; no going-concern qualifications; clean opinions.",
                "priority": "required",
                "sort_order": 60,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "Management accounts (current year)",
                "description": "YTD unaudited management accounts; no material variance from budget.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "Management accounts within 60 days; variance from budget < 10% on EBITDA.",
                "priority": "required",
                "sort_order": 70,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "Financial projections and base case model",
                "description": "5-year projections; DSCR and interest coverage analysis.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "DSCR ≥1.25x in base; interest coverage ≥2.0x; downside scenario reviewed.",
                "priority": "required",
                "sort_order": 80,
                "estimated_time_hours": 8.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "Existing debt and liabilities schedule",
                "description": "Full schedule of existing indebtedness, maturities, covenants.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "All existing debt confirmed; no undisclosed off-balance sheet obligations.",
                "priority": "required",
                "sort_order": 90,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "Collateral valuation",
                "description": "Independent valuation of pledged assets.",
                "requirement_type": "document_review",
                "required_document_types": ["valuation"],
                "verification_criteria": "LTV ≤ agreed maximum; valuation by independent appraiser within 6 months.",
                "priority": "required",
                "sort_order": 100,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            # Technical
            {
                "category": "technical",
                "name": "Business plan and market analysis",
                "description": "Review business plan, market position, competitive dynamics.",
                "requirement_type": "document_review",
                "required_document_types": ["business_plan"],
                "verification_criteria": "Business plan realistic; market assumptions independently verifiable; management team credible.",
                "priority": "required",
                "sort_order": 110,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Management team and key-person risk",
                "description": "CVs, track record, key-man insurance, succession plan.",
                "requirement_type": "information",
                "required_document_types": ["business_plan"],
                "verification_criteria": "Key management identified; key-man insurance in place for critical individuals.",
                "priority": "required",
                "sort_order": 120,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            # Environmental (for ESG-linked credit)
            {
                "category": "environmental",
                "name": "ESG due diligence",
                "description": "Environmental and social impact screening; ESG covenant compliance.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "No material ESG red flags; IFC Performance Standards checklist completed.",
                "priority": "recommended",
                "sort_order": 130,
                "estimated_time_hours": 4.0,
                "regulatory_reference": "IFC Performance Standards",
            },
            # Regulatory
            {
                "category": "regulatory",
                "name": "Regulatory and licensing review",
                "description": "Borrower licenses and regulatory status in all jurisdictions.",
                "requirement_type": "document_review",
                "required_document_types": ["permit"],
                "verification_criteria": "All material licenses valid; no pending enforcement actions.",
                "priority": "required",
                "sort_order": 140,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            {
                "category": "regulatory",
                "name": "Covenant compliance certificate",
                "description": "Compliance certificate for existing credit facilities.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "Compliance confirmed for all financial covenants in existing facilities.",
                "priority": "required",
                "sort_order": 150,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "regulatory",
                "name": "AML / KYC screening",
                "description": "Full AML/KYC on borrower entity, shareholders, and UBOs.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "KYC passed; PEP and sanctions screening clean; source of funds confirmed.",
                "priority": "required",
                "sort_order": 160,
                "estimated_time_hours": 4.0,
                "regulatory_reference": "FATF Recommendations",
            },
            # Insurance
            {
                "category": "insurance",
                "name": "Key-man and D&O insurance",
                "description": "D&O liability and key-person life insurance.",
                "requirement_type": "document_review",
                "required_document_types": ["insurance"],
                "verification_criteria": "D&O policy in place; key-man cover = loan amount for critical individuals.",
                "priority": "required",
                "sort_order": 170,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "insurance",
                "name": "Business interruption insurance",
                "description": "BI cover for operational borrowers.",
                "requirement_type": "document_review",
                "required_document_types": ["insurance"],
                "verification_criteria": "BI policy ≥ 12 months EBITDA; lender named as loss payee.",
                "priority": "recommended",
                "sort_order": 180,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
        ],
    },

    # ── Infrastructure / full_dd / global ────────────────────────────────────
    {
        "asset_type": "infrastructure",
        "deal_stage": "full_dd",
        "jurisdiction_group": None,
        "name": "Infrastructure — Full Due Diligence (Global)",
        "description": "Comprehensive due diligence checklist for infrastructure assets (PPP, concessions, regulated assets).",
        "items": [
            # Legal
            {
                "category": "legal",
                "name": "Concession / PPP agreement",
                "description": "Full review of concession or PPP contract: duration, revenue mechanism, step-in rights.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Concession term ≥ 20 years; force majeure and termination provisions investor-friendly.",
                "priority": "required",
                "sort_order": 10,
                "estimated_time_hours": 16.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Government / grantor credit review",
                "description": "Counterparty credit risk of the sovereign or sub-sovereign grantor.",
                "requirement_type": "information",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "Grantor sovereign rating ≥ BB-; payment record reviewed; political risk insurance considered.",
                "priority": "required",
                "sort_order": 20,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "EPC and O&M contracts",
                "description": "Construction and operations contracts with performance guarantees.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Fixed-price EPC; long-term O&M with availability SLAs.",
                "priority": "required",
                "sort_order": 30,
                "estimated_time_hours": 8.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Corporate structure and ownership",
                "description": "SPV structure, UBOs, no sanctioned shareholders.",
                "requirement_type": "document_review",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Clear ownership chain; UBO declaration; sanctions cleared.",
                "priority": "required",
                "sort_order": 40,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            # Financial
            {
                "category": "financial",
                "name": "Financial model — full lifecycle",
                "description": "Lifecycle financial model: construction, ramp-up, operations, handback.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "DSCR ≥1.20x; equity IRR benchmarked against infrastructure sector; model audited.",
                "priority": "required",
                "sort_order": 50,
                "estimated_time_hours": 20.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "3-year audited financial statements",
                "description": "Sponsor audited accounts.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "3 years audited; no going-concern qualifications.",
                "priority": "required",
                "sort_order": 60,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "Lifecycle cost analysis",
                "description": "Major maintenance and lifecycle capex schedule.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "Lifecycle costs benchmarked; renewal reserve adequately funded.",
                "priority": "required",
                "sort_order": 70,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            # Technical
            {
                "category": "technical",
                "name": "Demand / traffic study",
                "description": "Independent demand study with P50/P80 traffic or volume forecasts.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "Independent demand forecast; methodology reviewed; sensitivity to downside analysed.",
                "priority": "required",
                "sort_order": 80,
                "estimated_time_hours": 10.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Technical due diligence — engineering review",
                "description": "Independent engineer review of design, construction plans, cost estimates.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "IE report confirms design is fit for purpose; cost estimates reasonable.",
                "priority": "required",
                "sort_order": 90,
                "estimated_time_hours": 16.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "O&M plan and asset management strategy",
                "description": "Detailed O&M plan covering maintenance schedules and lifecycle strategy.",
                "requirement_type": "document_review",
                "required_document_types": ["technical_study"],
                "verification_criteria": "O&M plan covers full asset life; major maintenance procedures documented.",
                "priority": "required",
                "sort_order": 100,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            # Environmental
            {
                "category": "environmental",
                "name": "Environmental and Social Impact Assessment",
                "description": "ESIA in line with IFC Performance Standards.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "ESIA approved; ESMP in place; no category A risks unmitigated.",
                "priority": "required",
                "sort_order": 110,
                "estimated_time_hours": 8.0,
                "regulatory_reference": "IFC Performance Standards",
            },
            {
                "category": "environmental",
                "name": "Equator Principles compliance (if applicable)",
                "description": "EP category assessment for projects > $10m.",
                "requirement_type": "document_review",
                "required_document_types": ["environmental_report"],
                "verification_criteria": "EP category assigned; compliance plan in place.",
                "priority": "recommended",
                "sort_order": 120,
                "estimated_time_hours": 4.0,
                "regulatory_reference": "Equator Principles IV",
            },
            # Regulatory
            {
                "category": "regulatory",
                "name": "Regulatory framework analysis",
                "description": "Review of regulatory regime: tariff-setting, rate reviews, regulatory risk.",
                "requirement_type": "information",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Regulatory framework documented; tariff reset risk quantified; precedent decisions reviewed.",
                "priority": "required",
                "sort_order": 130,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            {
                "category": "regulatory",
                "name": "All permits and approvals",
                "description": "Construction, operating, environmental permits.",
                "requirement_type": "document_review",
                "required_document_types": ["permit"],
                "verification_criteria": "All material permits in place; no appeals; permit conditions met in design.",
                "priority": "required",
                "sort_order": 140,
                "estimated_time_hours": 4.0,
                "regulatory_reference": None,
            },
            {
                "category": "regulatory",
                "name": "Political risk assessment",
                "description": "Country risk, expropriation risk, currency convertibility.",
                "requirement_type": "information",
                "required_document_types": ["other"],
                "verification_criteria": "Country risk rating; political risk insurance considered; mitigants documented.",
                "priority": "required",
                "sort_order": 150,
                "estimated_time_hours": 6.0,
                "regulatory_reference": None,
            },
            # Insurance
            {
                "category": "insurance",
                "name": "Construction insurance package",
                "description": "CAR, third-party liability, delay in start-up.",
                "requirement_type": "document_review",
                "required_document_types": ["insurance"],
                "verification_criteria": "CAR = 100% contract price; DSU cover ≥ 12 months debt service.",
                "priority": "required",
                "sort_order": 160,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            {
                "category": "insurance",
                "name": "Operational insurance package",
                "description": "Property, BI, third-party liability, political risk.",
                "requirement_type": "document_review",
                "required_document_types": ["insurance"],
                "verification_criteria": "Property cover ≥ replacement cost; BI ≥ 18 months; political risk if developing market.",
                "priority": "required",
                "sort_order": 170,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
            {
                "category": "insurance",
                "name": "Political risk / investment insurance",
                "description": "MIGA or equivalent political risk insurance for cross-border investments.",
                "requirement_type": "information",
                "required_document_types": ["insurance"],
                "verification_criteria": "PRI coverage ≥ equity invested; coverage for expropriation, war, transfer restriction.",
                "priority": "recommended",
                "sort_order": 180,
                "estimated_time_hours": 3.0,
                "regulatory_reference": None,
            },
        ],
    },

    # ── Solar / screening / global ───────────────────────────────────────────
    {
        "asset_type": "solar",
        "deal_stage": "screening",
        "jurisdiction_group": None,
        "name": "Solar PV — Screening Checklist (Global)",
        "description": "Lightweight screening checklist for initial evaluation of solar PV opportunities.",
        "items": [
            {
                "category": "legal",
                "name": "Site control / land rights",
                "description": "Confirm site control (option, LOI, or lease) exists.",
                "requirement_type": "information",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Site control document provided; term sufficient for development.",
                "priority": "required",
                "sort_order": 10,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "regulatory",
                "name": "Permitting status",
                "description": "Confirm planning/permitting status: pre-application, applied, approved.",
                "requirement_type": "information",
                "required_document_types": ["permit"],
                "verification_criteria": "Permitting timeline and status confirmed in writing.",
                "priority": "required",
                "sort_order": 20,
                "estimated_time_hours": 0.5,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Grid interconnection queue position",
                "description": "Confirm queue position and estimated interconnection cost.",
                "requirement_type": "information",
                "required_document_types": ["technical_study"],
                "verification_criteria": "Queue position confirmed; interconnection cost estimate available.",
                "priority": "required",
                "sort_order": 30,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Preliminary yield estimate",
                "description": "Preliminary P50 energy yield from solar resource data.",
                "requirement_type": "information",
                "required_document_types": ["technical_study"],
                "verification_criteria": "Yield estimate supported by recognised solar resource database (Solargis, PVGIS).",
                "priority": "required",
                "sort_order": 40,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "High-level financial summary",
                "description": "CAPEX estimate, expected IRR, and offtake price.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "Equity IRR ≥ minimum threshold; CAPEX per MW within market range.",
                "priority": "required",
                "sort_order": 50,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Offtake / revenue mechanism overview",
                "description": "Describe offtake strategy: PPA, merchant, subsidy.",
                "requirement_type": "information",
                "required_document_types": [],
                "verification_criteria": "Revenue mechanism identified; offtaker credit quality described.",
                "priority": "required",
                "sort_order": 60,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "environmental",
                "name": "Known environmental constraints",
                "description": "Identify any protected areas, endangered species, or contamination flags.",
                "requirement_type": "information",
                "required_document_types": [],
                "verification_criteria": "No material constraints identified; or plan to address constraints provided.",
                "priority": "recommended",
                "sort_order": 70,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Technology and equipment strategy",
                "description": "Proposed module and inverter technology; single-axis tracker consideration.",
                "requirement_type": "information",
                "required_document_types": [],
                "verification_criteria": "Bankable equipment strategy; technology risk acceptable.",
                "priority": "recommended",
                "sort_order": 80,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "Development timeline",
                "description": "Key milestones: permit, financial close, construction, COD.",
                "requirement_type": "information",
                "required_document_types": [],
                "verification_criteria": "Realistic timeline; COD date confirmed or estimated.",
                "priority": "required",
                "sort_order": 90,
                "estimated_time_hours": 0.5,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Developer track record",
                "description": "Sponsor/developer experience with comparable solar projects.",
                "requirement_type": "information",
                "required_document_types": [],
                "verification_criteria": "At least 1 comparable project delivered or in construction; references available.",
                "priority": "required",
                "sort_order": 100,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
        ],
    },

    # ── Wind / screening / global ────────────────────────────────────────────
    {
        "asset_type": "wind",
        "deal_stage": "screening",
        "jurisdiction_group": None,
        "name": "Onshore Wind — Screening Checklist (Global)",
        "description": "Lightweight screening checklist for initial evaluation of onshore wind opportunities.",
        "items": [
            {
                "category": "legal",
                "name": "Site control / land rights",
                "description": "Confirm site control (option, LOI, or lease) for all turbine positions.",
                "requirement_type": "information",
                "required_document_types": ["legal_agreement"],
                "verification_criteria": "Site control documents provided; no material gaps in site control.",
                "priority": "required",
                "sort_order": 10,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "regulatory",
                "name": "Permitting status",
                "description": "Confirm planning/permitting status.",
                "requirement_type": "information",
                "required_document_types": ["permit"],
                "verification_criteria": "Permitting status confirmed; timeline to permit realistic.",
                "priority": "required",
                "sort_order": 20,
                "estimated_time_hours": 0.5,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Wind resource preliminary assessment",
                "description": "Preliminary P50 wind speed and yield from reanalysis data.",
                "requirement_type": "information",
                "required_document_types": ["technical_study"],
                "verification_criteria": "Mean wind speed ≥ threshold for viability; resource data source identified.",
                "priority": "required",
                "sort_order": 30,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Grid connection feasibility",
                "description": "Confirm grid connection feasibility and estimated connection cost.",
                "requirement_type": "information",
                "required_document_types": [],
                "verification_criteria": "Grid capacity confirmed; connection cost within budget.",
                "priority": "required",
                "sort_order": 40,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "High-level financial summary",
                "description": "CAPEX per MW, expected IRR, offtake price.",
                "requirement_type": "document_review",
                "required_document_types": ["financial_statement"],
                "verification_criteria": "Equity IRR meets minimum; CAPEX per MW within market range.",
                "priority": "required",
                "sort_order": 50,
                "estimated_time_hours": 2.0,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Offtake strategy",
                "description": "Revenue mechanism: PPA, CfD, subsidy, or merchant.",
                "requirement_type": "information",
                "required_document_types": [],
                "verification_criteria": "Revenue mechanism identified; offtaker or subsidy scheme described.",
                "priority": "required",
                "sort_order": 60,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "environmental",
                "name": "Known environmental constraints",
                "description": "Protected areas, Natura 2000, noise-sensitive receptors, raptors.",
                "requirement_type": "information",
                "required_document_types": [],
                "verification_criteria": "No fatal-flaw environmental issues; constraints mapped.",
                "priority": "recommended",
                "sort_order": 70,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "technical",
                "name": "Turbine technology selection",
                "description": "Proposed turbine OEM and rated capacity.",
                "requirement_type": "information",
                "required_document_types": [],
                "verification_criteria": "Bankable OEM selected or shortlisted; rated capacity appropriate for wind regime.",
                "priority": "recommended",
                "sort_order": 80,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
            {
                "category": "financial",
                "name": "Development timeline",
                "description": "Key milestones to financial close and COD.",
                "requirement_type": "information",
                "required_document_types": [],
                "verification_criteria": "Timeline realistic; COD date estimated.",
                "priority": "required",
                "sort_order": 90,
                "estimated_time_hours": 0.5,
                "regulatory_reference": None,
            },
            {
                "category": "legal",
                "name": "Developer track record",
                "description": "Sponsor experience with comparable wind projects.",
                "requirement_type": "information",
                "required_document_types": [],
                "verification_criteria": "At least 1 comparable wind project delivered or under construction.",
                "priority": "required",
                "sort_order": 100,
                "estimated_time_hours": 1.0,
                "regulatory_reference": None,
            },
        ],
    },
]


async def seed_dd_templates(db: AsyncSession) -> None:
    """Insert seed DD templates and items. Idempotent — skips existing."""
    seeded_templates = 0
    skipped_templates = 0
    seeded_items = 0

    for tpl_data in TEMPLATES:
        # Check if template already exists
        existing = await db.execute(
            select(DDChecklistTemplate).where(
                DDChecklistTemplate.asset_type == tpl_data["asset_type"],
                DDChecklistTemplate.deal_stage == tpl_data["deal_stage"],
                DDChecklistTemplate.jurisdiction_group == tpl_data["jurisdiction_group"],
                DDChecklistTemplate.name == tpl_data["name"],
                DDChecklistTemplate.is_deleted.is_(False),
            )
        )
        if existing.scalar_one_or_none():
            skipped_templates += 1
            continue

        items_data = tpl_data.pop("items", [])
        template = DDChecklistTemplate(**tpl_data)
        db.add(template)
        await db.flush()  # get the generated ID

        for item_data in items_data:
            item = DDChecklistItem(template_id=template.id, **item_data)
            db.add(item)
            seeded_items += 1

        seeded_templates += 1

    await db.commit()
    logger.info(
        "seed_dd_templates.complete",
        seeded_templates=seeded_templates,
        skipped_templates=skipped_templates,
        seeded_items=seeded_items,
    )
