"use client";

import { useState } from "react";
import { CheckCircle2, ClipboardCopy, FileText, Loader2, RefreshCw, Sparkles } from "lucide-react";
import {
  Badge,
  Button,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  EmptyState,
} from "@scr/ui";
import {
  BUSINESS_PLAN_ACTIONS,
  useGenerateBusinessPlan,
  useBusinessPlanResult,
  type BusinessPlanActionKey,
} from "@/lib/business-plan";
import { useProjects } from "@/lib/projects";

// ── Section Card ──────────────────────────────────────────────────────────

function SectionCard({
  actionKey,
  projectId,
}: {
  actionKey: BusinessPlanActionKey;
  projectId: string;
}) {
  const action = BUSINESS_PLAN_ACTIONS[actionKey];
  const generate = useGenerateBusinessPlan(projectId);
  const [taskLogId, setTaskLogId] = useState<string | undefined>();
  const [copied, setCopied] = useState(false);

  const { data: result } = useBusinessPlanResult(projectId, taskLogId);

  const isLoading = generate.isPending || result?.status === "pending" || result?.status === "processing";
  const content = result?.status === "completed" ? result.content : null;

  const handleGenerate = () => {
    generate.mutate(actionKey, {
      onSuccess: (data) => setTaskLogId(data.task_log_id),
    });
  };

  const handleCopy = () => {
    if (content) {
      navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-sm flex items-center gap-2">
            <span>{action.icon}</span>
            {action.label}
          </CardTitle>
          <div className="flex items-center gap-2">
            {content && (
              <button
                onClick={handleCopy}
                className="text-neutral-400 hover:text-neutral-600"
                title="Copy to clipboard"
              >
                {copied ? (
                  <CheckCircle2 className="h-4 w-4 text-green-500" />
                ) : (
                  <ClipboardCopy className="h-4 w-4" />
                )}
              </button>
            )}
            <Button
              variant="outline"
              onClick={handleGenerate}
              disabled={isLoading || !projectId}
              className="h-7 text-xs px-2"
            >
              {isLoading ? (
                <Loader2 className="h-3 w-3 animate-spin mr-1" />
              ) : content ? (
                <RefreshCw className="h-3 w-3 mr-1" />
              ) : (
                <Sparkles className="h-3 w-3 mr-1" />
              )}
              {content ? "Regenerate" : "Generate"}
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <p className="text-xs text-neutral-500 mb-3">{action.description}</p>
        {isLoading ? (
          <div className="flex items-center gap-2 text-xs text-neutral-400 py-4">
            <Loader2 className="h-4 w-4 animate-spin" />
            Generating with Claude AI…
          </div>
        ) : content ? (
          <div className="text-sm text-neutral-800 leading-relaxed whitespace-pre-wrap bg-neutral-50 rounded-lg p-4 border">
            {content}
          </div>
        ) : (
          <div className="text-xs text-neutral-400 py-4 text-center border border-dashed rounded-lg">
            Click Generate to create AI content
          </div>
        )}
        {result?.model_used && content && (
          <p className="text-[10px] text-neutral-400 mt-2">
            Generated by {result.model_used}
          </p>
        )}
      </CardContent>
    </Card>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────

export default function BusinessPlanPage() {
  const [selectedProjectId, setSelectedProjectId] = useState("");
  const { data: projects } = useProjects({ limit: 50 });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-primary-100 rounded-lg">
            <FileText className="h-6 w-6 text-primary-600" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-neutral-900">
              Business Planning AI
            </h1>
            <p className="text-sm text-neutral-500 mt-0.5">
              Generate investor-ready content for your project using Claude AI
            </p>
          </div>
        </div>

        {/* Project selector */}
        <select
          className="text-sm border border-neutral-200 rounded-lg px-3 py-2 bg-white"
          value={selectedProjectId}
          onChange={(e) => setSelectedProjectId(e.target.value)}
        >
          <option value="">Select a project…</option>
          {projects?.items.map((p) => (
            <option key={p.id} value={p.id}>
              {p.name}
            </option>
          ))}
        </select>
      </div>

      {!selectedProjectId ? (
        <EmptyState
          icon={<FileText className="h-12 w-12 text-neutral-400" />}
          title="Select a project"
          description="Choose a project from the dropdown to generate AI-powered business plan sections."
        />
      ) : (
        <>
          <div className="flex items-center gap-2">
            <Badge variant="info">
              {projects?.items.find((p) => p.id === selectedProjectId)?.name}
            </Badge>
            <span className="text-xs text-neutral-500">
              Select sections to generate below
            </span>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {(
              Object.keys(BUSINESS_PLAN_ACTIONS) as BusinessPlanActionKey[]
            ).map((actionKey) => (
              <SectionCard
                key={actionKey}
                actionKey={actionKey}
                projectId={selectedProjectId}
              />
            ))}
          </div>
        </>
      )}
    </div>
  );
}
