"""initial schema - 36 tables

Revision ID: 394135f84e64
Revises: 
Create Date: 2026-02-27 07:49:15.405959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '394135f84e64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('INVESTOR', 'ALLY', 'ADMIN', name='orgtype'), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('subscription_tier', sa.Enum('FOUNDATION', 'PROFESSIONAL', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'TRIAL', 'SUSPENDED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=True)
    op.create_index('ix_organizations_type', 'organizations', ['type'], unique=False)
    op.create_table('investor_mandates',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('sectors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('geographies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('stages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ticket_size_min', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('ticket_size_max', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('target_irr_min', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('risk_tolerance', sa.Enum('CONSERVATIVE', 'MODERATE', 'AGGRESSIVE', name='risktolerance'), nullable=False),
    sa.Column('esg_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investor_mandates_is_active', 'investor_mandates', ['org_id', 'is_active'], unique=False)
    op.create_index('ix_investor_mandates_org_id', 'investor_mandates', ['org_id'], unique=False)
    op.create_table('legal_templates',
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('doc_type', sa.Enum('TERM_SHEET', 'SUBSCRIPTION_AGREEMENT', 'SPV_INCORPORATION', 'NDA', 'SIDE_LETTER', 'AMENDMENT', name='legaldocumenttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_templates_doc_type', 'legal_templates', ['doc_type'], unique=False)
    op.create_index('ix_legal_templates_org_id', 'legal_templates', ['org_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strategy', sa.Enum('IMPACT', 'GROWTH', 'INCOME', 'BALANCED', 'OPPORTUNISTIC', name='portfoliostrategy'), nullable=False),
    sa.Column('fund_type', sa.Enum('OPEN_END', 'CLOSED_END', 'EVERGREEN', 'SPV', name='fundtype'), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=True),
    sa.Column('target_aum', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('current_aum', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sfdr_classification', sa.Enum('ARTICLE_6', 'ARTICLE_8', 'ARTICLE_9', 'NOT_APPLICABLE', name='sfdrclassification'), nullable=False),
    sa.Column('status', sa.Enum('FUNDRAISING', 'INVESTING', 'FULLY_INVESTED', 'HARVESTING', 'LIQUIDATED', name='portfoliostatus'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolios_org_id', 'portfolios', ['org_id'], unique=False)
    op.create_index('ix_portfolios_org_id_status', 'portfolios', ['org_id', 'status'], unique=False)
    op.create_index('ix_portfolios_status', 'portfolios', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_type', sa.Enum('SOLAR', 'WIND', 'HYDRO', 'BIOMASS', 'GEOTHERMAL', 'ENERGY_EFFICIENCY', 'GREEN_BUILDING', 'SUSTAINABLE_AGRICULTURE', 'OTHER', name='projecttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'FUNDRAISING', 'FUNDED', 'CONSTRUCTION', 'OPERATIONAL', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('stage', sa.Enum('CONCEPT', 'PRE_DEVELOPMENT', 'DEVELOPMENT', 'CONSTRUCTION_READY', 'UNDER_CONSTRUCTION', 'OPERATIONAL', name='projectstage'), nullable=False),
    sa.Column('geography_country', sa.String(length=100), nullable=False),
    sa.Column('geography_region', sa.String(length=255), nullable=False),
    sa.Column('geography_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technology_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capacity_mw', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('total_investment_required', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('target_close_date', sa.Date(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_geography_country', 'projects', ['geography_country'], unique=False)
    op.create_index('ix_projects_org_id', 'projects', ['org_id'], unique=False)
    op.create_index('ix_projects_org_id_status', 'projects', ['org_id', 'status'], unique=False)
    op.create_index('ix_projects_project_type', 'projects', ['project_type'], unique=False)
    op.create_index('ix_projects_slug', 'projects', ['slug'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('report_templates',
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('PERFORMANCE', 'ESG', 'COMPLIANCE', 'PORTFOLIO', 'PROJECT', 'CUSTOM', name='reportcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('template_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_templates_category', 'report_templates', ['category'], unique=False)
    op.create_index('ix_report_templates_org_id', 'report_templates', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('external_auth_id', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_auth_id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_external_auth_id', 'users', ['external_auth_id'], unique=True)
    op.create_index('ix_users_org_id', 'users', ['org_id'], unique=False)
    op.create_index('ix_users_org_id_role', 'users', ['org_id', 'role'], unique=False)
    op.create_table('activities',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_entity', 'activities', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_activities_org_id', 'activities', ['org_id'], unique=False)
    op.create_index('ix_activities_org_id_created_at', 'activities', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_activities_user_id', 'activities', ['user_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('context_type', sa.Enum('GENERAL', 'PROJECT', 'PORTFOLIO', 'DATAROOM', 'DEAL', name='aicontexttype'), nullable=False),
    sa.Column('context_entity_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_conversations_context_type', 'ai_conversations', ['context_type'], unique=False)
    op.create_index('ix_ai_conversations_org_id', 'ai_conversations', ['org_id'], unique=False)
    op.create_index('ix_ai_conversations_user_context', 'ai_conversations', ['user_id', 'context_type'], unique=False)
    op.create_index('ix_ai_conversations_user_id', 'ai_conversations', ['user_id'], unique=False)
    op.create_table('ai_task_logs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('DOCUMENT_INTELLIGENCE', 'SCORING', 'FINANCIAL', 'MATCHING', 'REPORT', 'CONVERSATIONAL', 'COMPLIANCE', name='aiagenttype'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='aitaskstatus'), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_task_logs_agent_type', 'ai_task_logs', ['agent_type'], unique=False)
    op.create_index('ix_ai_task_logs_entity', 'ai_task_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_ai_task_logs_org_id', 'ai_task_logs', ['org_id'], unique=False)
    op.create_index('ix_ai_task_logs_status', 'ai_task_logs', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_org_id', 'audit_logs', ['org_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('business_plans',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('financial_projections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'FINALIZED', name='businessplanstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_business_plans_org_id', 'business_plans', ['org_id'], unique=False)
    op.create_index('ix_business_plans_project_id', 'business_plans', ['project_id'], unique=False)
    op.create_index('ix_business_plans_status', 'business_plans', ['status'], unique=False)
    op.create_table('carbon_credits',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('registry', sa.String(length=100), nullable=False),
    sa.Column('methodology', sa.String(length=255), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=False),
    sa.Column('quantity_tons', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('price_per_ton', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.Enum('ESTIMATED', 'SUBMITTED', 'VERIFIED', 'ISSUED', 'RETIRED', name='carbonverificationstatus'), nullable=False),
    sa.Column('verification_body', sa.String(length=255), nullable=True),
    sa.Column('issuance_date', sa.Date(), nullable=True),
    sa.Column('retirement_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_carbon_credits_org_id', 'carbon_credits', ['org_id'], unique=False)
    op.create_index('ix_carbon_credits_project_id', 'carbon_credits', ['project_id'], unique=False)
    op.create_index('ix_carbon_credits_verification_status', 'carbon_credits', ['verification_status'], unique=False)
    op.create_table('comments',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_entity', 'comments', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_comments_org_id', 'comments', ['org_id'], unique=False)
    op.create_index('ix_comments_parent_id', 'comments', ['parent_id'], unique=False)
    op.create_index('ix_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_table('document_folders',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('parent_folder_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['document_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_folders_org_id', 'document_folders', ['org_id'], unique=False)
    op.create_index('ix_document_folders_parent', 'document_folders', ['parent_folder_id'], unique=False)
    op.create_index('ix_document_folders_project_id', 'document_folders', ['project_id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'GENERATING', 'READY', 'ERROR', name='reportstatus'), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('s3_key', sa.String(length=1000), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_reports_org_id', 'generated_reports', ['org_id'], unique=False)
    op.create_index('ix_generated_reports_org_id_status', 'generated_reports', ['org_id', 'status'], unique=False)
    op.create_index('ix_generated_reports_status', 'generated_reports', ['status'], unique=False)
    op.create_index('ix_generated_reports_template_id', 'generated_reports', ['template_id'], unique=False)
    op.create_table('legal_documents',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('doc_type', sa.Enum('TERM_SHEET', 'SUBSCRIPTION_AGREEMENT', 'SPV_INCORPORATION', 'NDA', 'SIDE_LETTER', 'AMENDMENT', name='legaldocumenttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'SENT', 'SIGNED', 'EXECUTED', 'EXPIRED', name='legaldocumentstatus'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=True),
    sa.Column('counterparty_org_id', sa.UUID(), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['counterparty_org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['legal_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_documents_doc_type', 'legal_documents', ['doc_type'], unique=False)
    op.create_index('ix_legal_documents_org_id', 'legal_documents', ['org_id'], unique=False)
    op.create_index('ix_legal_documents_org_id_status', 'legal_documents', ['org_id', 'status'], unique=False)
    op.create_index('ix_legal_documents_project_id', 'legal_documents', ['project_id'], unique=False)
    op.create_index('ix_legal_documents_status', 'legal_documents', ['status'], unique=False)
    op.create_table('listings',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('listing_type', sa.Enum('EQUITY_SALE', 'DEBT_SALE', 'CO_INVESTMENT', 'CARBON_CREDIT', name='listingtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'UNDER_NEGOTIATION', 'SOLD', 'WITHDRAWN', 'EXPIRED', name='listingstatus'), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'QUALIFIED_ONLY', 'INVITE_ONLY', name='listingvisibility'), nullable=False),
    sa.Column('asking_price', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('minimum_investment', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listings_listing_type', 'listings', ['listing_type'], unique=False)
    op.create_index('ix_listings_org_id', 'listings', ['org_id'], unique=False)
    op.create_index('ix_listings_org_id_status', 'listings', ['org_id', 'status'], unique=False)
    op.create_index('ix_listings_project_id', 'listings', ['project_id'], unique=False)
    op.create_index('ix_listings_status', 'listings', ['status'], unique=False)
    op.create_index('ix_listings_visibility', 'listings', ['visibility'], unique=False)
    op.create_table('match_results',
    sa.Column('investor_org_id', sa.UUID(), nullable=False),
    sa.Column('ally_org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('SUGGESTED', 'VIEWED', 'INTERESTED', 'INTRO_REQUESTED', 'ENGAGED', 'PASSED', 'DECLINED', name='matchstatus'), nullable=False),
    sa.Column('initiated_by', sa.Enum('SYSTEM', 'INVESTOR', 'ALLY', name='matchinitiator'), nullable=False),
    sa.Column('investor_notes', sa.Text(), nullable=False),
    sa.Column('ally_notes', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['ally_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investor_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandate_id'], ['investor_mandates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_results_ally_org_id', 'match_results', ['ally_org_id'], unique=False)
    op.create_index('ix_match_results_ally_status', 'match_results', ['ally_org_id', 'status'], unique=False)
    op.create_index('ix_match_results_investor_org_id', 'match_results', ['investor_org_id'], unique=False)
    op.create_index('ix_match_results_investor_status', 'match_results', ['investor_org_id', 'status'], unique=False)
    op.create_index('ix_match_results_project_id', 'match_results', ['project_id'], unique=False)
    op.create_index('ix_match_results_status', 'match_results', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'ACTION_REQUIRED', 'MENTION', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=1000), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_org_id', 'notifications', ['org_id'], unique=False)
    op.create_index('ix_notifications_user_id_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('asset_name', sa.String(length=500), nullable=False),
    sa.Column('asset_type', sa.Enum('EQUITY', 'DEBT', 'MEZZANINE', 'PREFERRED', 'CONVERTIBLE', name='assettype'), nullable=False),
    sa.Column('investment_date', sa.Date(), nullable=False),
    sa.Column('investment_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('ownership_pct', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXITED', 'WRITTEN_OFF', 'PENDING', name='holdingstatus'), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_holdings_portfolio_id', 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_holdings_portfolio_id_status', 'portfolio_holdings', ['portfolio_id', 'status'], unique=False)
    op.create_index('ix_portfolio_holdings_project_id', 'portfolio_holdings', ['project_id'], unique=False)
    op.create_index('ix_portfolio_holdings_status', 'portfolio_holdings', ['status'], unique=False)
    op.create_table('portfolio_metrics',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('irr_gross', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('irr_net', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('moic', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('tvpi', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('dpi', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('rvpi', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('total_invested', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_distributions', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('cash_flows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('esg_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('carbon_reduction_tons', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_metrics_as_of_date', 'portfolio_metrics', ['portfolio_id', 'as_of_date'], unique=False)
    op.create_index('ix_portfolio_metrics_portfolio_id', 'portfolio_metrics', ['portfolio_id'], unique=False)
    op.create_table('project_budget_items',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'COMMITTED', 'PAID', name='budgetitemstatus'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_budget_items_project_id', 'project_budget_items', ['project_id'], unique=False)
    op.create_table('project_milestones',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', 'BLOCKED', name='milestonestatus'), nullable=False),
    sa.Column('completion_pct', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_milestones_project_id', 'project_milestones', ['project_id'], unique=False)
    op.create_index('ix_project_milestones_status', 'project_milestones', ['status'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('entity_type', sa.Enum('PROJECT', 'PORTFOLIO', 'HOLDING', name='riskentitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('risk_type', sa.Enum('MARKET', 'CREDIT', 'OPERATIONAL', 'REGULATORY', 'CLIMATE', 'CONCENTRATION', 'COUNTERPARTY', 'LIQUIDITY', name='risktype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='riskseverity'), nullable=False),
    sa.Column('probability', sa.Enum('UNLIKELY', 'POSSIBLE', 'LIKELY', 'VERY_LIKELY', name='riskprobability'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('IDENTIFIED', 'MONITORING', 'MITIGATED', 'ACCEPTED', name='riskassessmentstatus'), nullable=False),
    sa.Column('assessed_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessments_entity', 'risk_assessments', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_risk_assessments_org_id', 'risk_assessments', ['org_id'], unique=False)
    op.create_index('ix_risk_assessments_risk_type', 'risk_assessments', ['risk_type'], unique=False)
    op.create_index('ix_risk_assessments_severity', 'risk_assessments', ['severity'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', name='reportfrequency'), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_reports_is_active', 'scheduled_reports', ['org_id', 'is_active'], unique=False)
    op.create_index('ix_scheduled_reports_org_id', 'scheduled_reports', ['org_id'], unique=False)
    op.create_index('ix_scheduled_reports_template_id', 'scheduled_reports', ['template_id'], unique=False)
    op.create_table('signal_scores',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=False),
    sa.Column('financial_score', sa.Integer(), nullable=False),
    sa.Column('esg_score', sa.Integer(), nullable=False),
    sa.Column('regulatory_score', sa.Integer(), nullable=False),
    sa.Column('team_score', sa.Integer(), nullable=False),
    sa.Column('scoring_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_scores_project_id', 'signal_scores', ['project_id'], unique=False)
    op.create_index('ix_signal_scores_project_id_version', 'signal_scores', ['project_id', 'version'], unique=False)
    op.create_table('tax_credits',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('credit_type', sa.String(length=100), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('claimed_value', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('qualification', sa.Enum('POTENTIAL', 'QUALIFIED', 'CLAIMED', 'TRANSFERRED', name='taxcreditqualification'), nullable=False),
    sa.Column('qualification_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tax_credits_org_id', 'tax_credits', ['org_id'], unique=False)
    op.create_index('ix_tax_credits_project_id', 'tax_credits', ['project_id'], unique=False)
    op.create_index('ix_tax_credits_qualification', 'tax_credits', ['qualification'], unique=False)
    op.create_table('valuations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Enum('DCF', 'COMPARABLES', 'REPLACEMENT_COST', 'BOOK_VALUE', 'MARKET_VALUE', 'BLENDED', name='valuationmethod'), nullable=False),
    sa.Column('enterprise_value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('equity_value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'APPROVED', 'SUPERSEDED', name='valuationstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('valued_at', sa.Date(), nullable=False),
    sa.Column('prepared_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prepared_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_valuations_org_id', 'valuations', ['org_id'], unique=False)
    op.create_index('ix_valuations_project_id', 'valuations', ['project_id'], unique=False)
    op.create_index('ix_valuations_project_id_version', 'valuations', ['project_id', 'version'], unique=False)
    op.create_index('ix_valuations_status', 'valuations', ['status'], unique=False)
    op.create_table('ai_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL_CALL', 'TOOL_RESULT', name='aimessagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_messages_conversation_id', 'ai_messages', ['conversation_id'], unique=False)
    op.create_index('ix_ai_messages_role', 'ai_messages', ['role'], unique=False)
    op.create_table('documents',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'READY', 'ERROR', 'ARCHIVED', name='documentstatus'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('watermark_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['document_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_folder_id', 'documents', ['folder_id'], unique=False)
    op.create_index('ix_documents_org_id', 'documents', ['org_id'], unique=False)
    op.create_index('ix_documents_org_id_status', 'documents', ['org_id', 'status'], unique=False)
    op.create_index('ix_documents_portfolio_id', 'documents', ['portfolio_id'], unique=False)
    op.create_index('ix_documents_project_id', 'documents', ['project_id'], unique=False)
    op.create_index('ix_documents_uploaded_by', 'documents', ['uploaded_by'], unique=False)
    op.create_table('match_messages',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_messages_match_id', 'match_messages', ['match_id'], unique=False)
    op.create_index('ix_match_messages_sender_id', 'match_messages', ['sender_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_org_id', sa.UUID(), nullable=False),
    sa.Column('proposed_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('proposed_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'COUNTERED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='rfqstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('counter_price', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('counter_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['buyer_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfqs_buyer_org_id', 'rfqs', ['buyer_org_id'], unique=False)
    op.create_index('ix_rfqs_buyer_status', 'rfqs', ['buyer_org_id', 'status'], unique=False)
    op.create_index('ix_rfqs_listing_id', 'rfqs', ['listing_id'], unique=False)
    op.create_index('ix_rfqs_status', 'rfqs', ['status'], unique=False)
    op.create_table('document_access_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('VIEW', 'DOWNLOAD', 'SHARE', 'PRINT', name='documentaccessaction'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_access_logs_document_id', 'document_access_logs', ['document_id'], unique=False)
    op.create_index('ix_document_access_logs_org_id', 'document_access_logs', ['org_id'], unique=False)
    op.create_index('ix_document_access_logs_timestamp', 'document_access_logs', ['timestamp'], unique=False)
    op.create_index('ix_document_access_logs_user_id', 'document_access_logs', ['user_id'], unique=False)
    op.create_table('document_extractions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('extraction_type', sa.Enum('KPI', 'CLAUSE', 'DEADLINE', 'FINANCIAL', 'CLASSIFICATION', 'SUMMARY', name='extractiontype'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_extractions_document_id', 'document_extractions', ['document_id'], unique=False)
    op.create_index('ix_document_extractions_type', 'document_extractions', ['extraction_type'], unique=False)
    op.create_table('transactions',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_org_id', sa.UUID(), nullable=False),
    sa.Column('seller_org_id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='transactionstatus'), nullable=False),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settlement_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['buyer_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_buyer_org_id', 'transactions', ['buyer_org_id'], unique=False)
    op.create_index('ix_transactions_listing_id', 'transactions', ['listing_id'], unique=False)
    op.create_index('ix_transactions_seller_org_id', 'transactions', ['seller_org_id'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index('ix_transactions_seller_org_id', table_name='transactions')
    op.drop_index('ix_transactions_listing_id', table_name='transactions')
    op.drop_index('ix_transactions_buyer_org_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_document_extractions_type', table_name='document_extractions')
    op.drop_index('ix_document_extractions_document_id', table_name='document_extractions')
    op.drop_table('document_extractions')
    op.drop_index('ix_document_access_logs_user_id', table_name='document_access_logs')
    op.drop_index('ix_document_access_logs_timestamp', table_name='document_access_logs')
    op.drop_index('ix_document_access_logs_org_id', table_name='document_access_logs')
    op.drop_index('ix_document_access_logs_document_id', table_name='document_access_logs')
    op.drop_table('document_access_logs')
    op.drop_index('ix_rfqs_status', table_name='rfqs')
    op.drop_index('ix_rfqs_listing_id', table_name='rfqs')
    op.drop_index('ix_rfqs_buyer_status', table_name='rfqs')
    op.drop_index('ix_rfqs_buyer_org_id', table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index('ix_match_messages_sender_id', table_name='match_messages')
    op.drop_index('ix_match_messages_match_id', table_name='match_messages')
    op.drop_table('match_messages')
    op.drop_index('ix_documents_uploaded_by', table_name='documents')
    op.drop_index('ix_documents_project_id', table_name='documents')
    op.drop_index('ix_documents_portfolio_id', table_name='documents')
    op.drop_index('ix_documents_org_id_status', table_name='documents')
    op.drop_index('ix_documents_org_id', table_name='documents')
    op.drop_index('ix_documents_folder_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_ai_messages_role', table_name='ai_messages')
    op.drop_index('ix_ai_messages_conversation_id', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index('ix_valuations_status', table_name='valuations')
    op.drop_index('ix_valuations_project_id_version', table_name='valuations')
    op.drop_index('ix_valuations_project_id', table_name='valuations')
    op.drop_index('ix_valuations_org_id', table_name='valuations')
    op.drop_table('valuations')
    op.drop_index('ix_tax_credits_qualification', table_name='tax_credits')
    op.drop_index('ix_tax_credits_project_id', table_name='tax_credits')
    op.drop_index('ix_tax_credits_org_id', table_name='tax_credits')
    op.drop_table('tax_credits')
    op.drop_index('ix_signal_scores_project_id_version', table_name='signal_scores')
    op.drop_index('ix_signal_scores_project_id', table_name='signal_scores')
    op.drop_table('signal_scores')
    op.drop_index('ix_scheduled_reports_template_id', table_name='scheduled_reports')
    op.drop_index('ix_scheduled_reports_org_id', table_name='scheduled_reports')
    op.drop_index('ix_scheduled_reports_is_active', table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index('ix_risk_assessments_severity', table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_risk_type', table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_org_id', table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_entity', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('ix_project_milestones_status', table_name='project_milestones')
    op.drop_index('ix_project_milestones_project_id', table_name='project_milestones')
    op.drop_table('project_milestones')
    op.drop_index('ix_project_budget_items_project_id', table_name='project_budget_items')
    op.drop_table('project_budget_items')
    op.drop_index('ix_portfolio_metrics_portfolio_id', table_name='portfolio_metrics')
    op.drop_index('ix_portfolio_metrics_as_of_date', table_name='portfolio_metrics')
    op.drop_table('portfolio_metrics')
    op.drop_index('ix_portfolio_holdings_status', table_name='portfolio_holdings')
    op.drop_index('ix_portfolio_holdings_project_id', table_name='portfolio_holdings')
    op.drop_index('ix_portfolio_holdings_portfolio_id_status', table_name='portfolio_holdings')
    op.drop_index('ix_portfolio_holdings_portfolio_id', table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index('ix_notifications_user_id_is_read', table_name='notifications')
    op.drop_index('ix_notifications_org_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_match_results_status', table_name='match_results')
    op.drop_index('ix_match_results_project_id', table_name='match_results')
    op.drop_index('ix_match_results_investor_status', table_name='match_results')
    op.drop_index('ix_match_results_investor_org_id', table_name='match_results')
    op.drop_index('ix_match_results_ally_status', table_name='match_results')
    op.drop_index('ix_match_results_ally_org_id', table_name='match_results')
    op.drop_table('match_results')
    op.drop_index('ix_listings_visibility', table_name='listings')
    op.drop_index('ix_listings_status', table_name='listings')
    op.drop_index('ix_listings_project_id', table_name='listings')
    op.drop_index('ix_listings_org_id_status', table_name='listings')
    op.drop_index('ix_listings_org_id', table_name='listings')
    op.drop_index('ix_listings_listing_type', table_name='listings')
    op.drop_table('listings')
    op.drop_index('ix_legal_documents_status', table_name='legal_documents')
    op.drop_index('ix_legal_documents_project_id', table_name='legal_documents')
    op.drop_index('ix_legal_documents_org_id_status', table_name='legal_documents')
    op.drop_index('ix_legal_documents_org_id', table_name='legal_documents')
    op.drop_index('ix_legal_documents_doc_type', table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_index('ix_generated_reports_template_id', table_name='generated_reports')
    op.drop_index('ix_generated_reports_status', table_name='generated_reports')
    op.drop_index('ix_generated_reports_org_id_status', table_name='generated_reports')
    op.drop_index('ix_generated_reports_org_id', table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index('ix_document_folders_project_id', table_name='document_folders')
    op.drop_index('ix_document_folders_parent', table_name='document_folders')
    op.drop_index('ix_document_folders_org_id', table_name='document_folders')
    op.drop_table('document_folders')
    op.drop_index('ix_comments_user_id', table_name='comments')
    op.drop_index('ix_comments_parent_id', table_name='comments')
    op.drop_index('ix_comments_org_id', table_name='comments')
    op.drop_index('ix_comments_entity', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_carbon_credits_verification_status', table_name='carbon_credits')
    op.drop_index('ix_carbon_credits_project_id', table_name='carbon_credits')
    op.drop_index('ix_carbon_credits_org_id', table_name='carbon_credits')
    op.drop_table('carbon_credits')
    op.drop_index('ix_business_plans_status', table_name='business_plans')
    op.drop_index('ix_business_plans_project_id', table_name='business_plans')
    op.drop_index('ix_business_plans_org_id', table_name='business_plans')
    op.drop_table('business_plans')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_ai_task_logs_status', table_name='ai_task_logs')
    op.drop_index('ix_ai_task_logs_org_id', table_name='ai_task_logs')
    op.drop_index('ix_ai_task_logs_entity', table_name='ai_task_logs')
    op.drop_index('ix_ai_task_logs_agent_type', table_name='ai_task_logs')
    op.drop_table('ai_task_logs')
    op.drop_index('ix_ai_conversations_user_id', table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_user_context', table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_org_id', table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_context_type', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index('ix_activities_user_id', table_name='activities')
    op.drop_index('ix_activities_org_id_created_at', table_name='activities')
    op.drop_index('ix_activities_org_id', table_name='activities')
    op.drop_index('ix_activities_entity', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_users_org_id_role', table_name='users')
    op.drop_index('ix_users_org_id', table_name='users')
    op.drop_index('ix_users_external_auth_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_report_templates_org_id', table_name='report_templates')
    op.drop_index('ix_report_templates_category', table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_slug', table_name='projects')
    op.drop_index('ix_projects_project_type', table_name='projects')
    op.drop_index('ix_projects_org_id_status', table_name='projects')
    op.drop_index('ix_projects_org_id', table_name='projects')
    op.drop_index('ix_projects_geography_country', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_portfolios_status', table_name='portfolios')
    op.drop_index('ix_portfolios_org_id_status', table_name='portfolios')
    op.drop_index('ix_portfolios_org_id', table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('ix_legal_templates_org_id', table_name='legal_templates')
    op.drop_index('ix_legal_templates_doc_type', table_name='legal_templates')
    op.drop_table('legal_templates')
    op.drop_index('ix_investor_mandates_org_id', table_name='investor_mandates')
    op.drop_index('ix_investor_mandates_is_active', table_name='investor_mandates')
    op.drop_table('investor_mandates')
    op.drop_index('ix_organizations_type', table_name='organizations')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
