"""add document classification and share_links table

Revision ID: cb877e7100cf
Revises: 394135f84e64
Create Date: 2026-02-27 09:11:42.488727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb877e7100cf'
down_revision: Union[str, None] = '394135f84e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_links',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('watermark_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_download', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index('ix_share_links_document_id', 'share_links', ['document_id'], unique=False)
    op.create_index('ix_share_links_org_id', 'share_links', ['org_id'], unique=False)
    op.create_index('ix_share_links_token', 'share_links', ['share_token'], unique=True)
    documentclassification = sa.Enum(
        'FINANCIAL_STATEMENT', 'LEGAL_AGREEMENT', 'TECHNICAL_STUDY',
        'ENVIRONMENTAL_REPORT', 'PERMIT', 'INSURANCE', 'VALUATION',
        'BUSINESS_PLAN', 'PRESENTATION', 'CORRESPONDENCE', 'OTHER',
        name='documentclassification',
    )
    documentclassification.create(op.get_bind(), checkfirst=True)
    op.add_column('documents', sa.Column('classification', documentclassification, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'classification')
    sa.Enum(name='documentclassification').drop(op.get_bind(), checkfirst=True)
    op.drop_index('ix_share_links_token', table_name='share_links')
    op.drop_index('ix_share_links_org_id', table_name='share_links')
    op.drop_index('ix_share_links_document_id', table_name='share_links')
    op.drop_table('share_links')
    # ### end Alembic commands ###
