"""fix backtest_runs org FK and register citations lineage models

Revision ID: fdb047fb791b
Revises: o1a2b3c4d5e6
Create Date: 2026-03-14 14:48:28.800100

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdb047fb791b"
down_revision: Union[str, None] = "o1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_output_feedback", "updated_at")
    op.drop_index(op.f("ix_ai_task_logs_confidence"), table_name="ai_task_logs")
    op.drop_index(op.f("ix_ai_task_logs_confidence_level"), table_name="ai_task_logs")
    op.drop_index(op.f("ix_ai_task_logs_org_status_time"), table_name="ai_task_logs")
    op.drop_constraint(op.f("fk_ai_task_logs_prompt_template"), "ai_task_logs", type_="foreignkey")
    op.drop_column("ai_task_logs", "confidence")
    op.drop_column("ai_task_logs", "validation_warnings")
    op.drop_column("ai_task_logs", "prompt_template_id")
    op.drop_column("ai_task_logs", "confidence_level")
    op.drop_column("ai_task_logs", "validation_repairs")
    op.drop_column("ai_task_logs", "prompt_version")
    op.drop_column("ai_task_logs", "processing_time_ms")
    op.drop_index(op.f("ix_audit_logs_org_time"), table_name="audit_logs")
    op.drop_index(op.f("ix_anchor_batch_id"), table_name="blockchain_anchors")
    op.drop_index(op.f("ix_anchor_event_type"), table_name="blockchain_anchors")
    op.drop_index(op.f("ix_anchor_tx_hash"), table_name="blockchain_anchors")
    op.create_index(
        op.f("ix_blockchain_anchors_batch_id"), "blockchain_anchors", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_blockchain_anchors_event_type"), "blockchain_anchors", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_blockchain_anchors_tx_hash"), "blockchain_anchors", ["tx_hash"], unique=False
    )
    op.drop_index(
        op.f("ix_comparable_transactions_asset_type"), table_name="comparable_transactions"
    )
    op.drop_index(
        op.f("ix_comparable_transactions_close_year"), table_name="comparable_transactions"
    )
    op.drop_constraint(op.f("custom_domains_org_id_fkey"), "custom_domains", type_="foreignkey")
    op.add_column(
        "data_review_queue",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
    )
    op.create_index(
        op.f("ix_deal_room_activities_room_id"), "deal_room_activities", ["room_id"], unique=False
    )
    op.create_index(
        op.f("ix_deal_room_members_room_id"), "deal_room_members", ["room_id"], unique=False
    )
    op.create_index(
        op.f("ix_deal_stage_transitions_org_id"), "deal_stage_transitions", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_deal_stage_transitions_project_id"),
        "deal_stage_transitions",
        ["project_id"],
        unique=False,
    )
    op.create_index(op.f("ix_digest_logs_org_id"), "digest_logs", ["org_id"], unique=False)
    op.drop_index(op.f("ix_doc_access_logs_doc_time"), table_name="document_access_logs")
    op.drop_index(op.f("ix_document_annotations_created_by"), table_name="document_annotations")
    op.drop_index(op.f("ix_document_annotations_document_id"), table_name="document_annotations")
    op.drop_index(op.f("ix_document_annotations_org_id"), table_name="document_annotations")
    op.drop_constraint(
        op.f("document_annotations_created_by_fkey"), "document_annotations", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("document_annotations_org_id_fkey"), "document_annotations", type_="foreignkey"
    )
    op.drop_index(op.f("ix_esg_metrics_org_period"), table_name="esg_metrics")
    op.drop_index(op.f("ix_feature_flag_overrides_flag_name"), table_name="feature_flag_overrides")
    op.drop_index(op.f("ix_feature_flag_overrides_org_id"), table_name="feature_flag_overrides")
    op.drop_index(op.f("ix_feature_flags_name"), table_name="feature_flags")
    op.alter_column(
        "financial_templates",
        "created_at",
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "financial_templates",
        "updated_at",
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_financial_templates_taxonomy"), table_name="financial_templates")
    op.create_index(
        op.f("ix_financial_templates_taxonomy_code"),
        "financial_templates",
        ["taxonomy_code"],
        unique=False,
    )
    op.alter_column(
        "industry_taxonomy", "created_at", nullable=False, existing_server_default=sa.text("now()")
    )
    op.alter_column(
        "industry_taxonomy", "updated_at", nullable=False, existing_server_default=sa.text("now()")
    )
    op.drop_index(op.f("ix_taxonomy_parent_code"), table_name="industry_taxonomy")
    op.create_index(
        op.f("ix_industry_taxonomy_parent_code"), "industry_taxonomy", ["parent_code"], unique=False
    )
    op.drop_index(op.f("ix_certification_project"), table_name="investor_readiness_certifications")
    op.create_index(
        op.f("ix_investor_readiness_certifications_project_id"),
        "investor_readiness_certifications",
        ["project_id"],
        unique=False,
    )
    op.drop_column("investor_risk_profiles", "updated_at")
    op.add_column(
        "market_data_processed",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "market_data_raw",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "market_data_sources",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "market_enrichment_fetch_logs",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
    )
    op.drop_constraint(op.f("fk_org_api_keys_org_id"), "org_api_keys", type_="foreignkey")
    op.drop_column("projects", "project_currency")
    op.add_column(
        "prompt_templates",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
    )
    op.drop_index(op.f("ix_redaction_jobs_document_id"), table_name="redaction_jobs")
    op.drop_index(op.f("ix_redaction_jobs_org_id"), table_name="redaction_jobs")
    op.drop_constraint(op.f("redaction_jobs_created_by_fkey"), "redaction_jobs", type_="foreignkey")
    op.drop_constraint(op.f("redaction_jobs_org_id_fkey"), "redaction_jobs", type_="foreignkey")
    op.drop_column("risk_mitigation_statuses", "updated_at")
    op.drop_index(op.f("ix_signal_scores_project_time"), table_name="signal_scores")
    op.drop_index(op.f("ix_usage_events_created_at"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_event_type"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_org_type_time"), table_name="usage_events")
    op.drop_index(op.f("ix_waitlist_entries_email"), table_name="waitlist_entries")
    op.drop_index(op.f("ix_waitlist_entries_status"), table_name="waitlist_entries")
    op.create_index(
        op.f("ix_watchlist_alerts_user_id"), "watchlist_alerts", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_webhook_deliveries_next_retry_at"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_org_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_status"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_status_retry"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_subscription_id"), table_name="webhook_deliveries")
    op.drop_constraint(
        op.f("webhook_deliveries_subscription_id_fkey"), "webhook_deliveries", type_="foreignkey"
    )
    op.drop_index(op.f("ix_webhook_subscriptions_org_id"), table_name="webhook_subscriptions")
    op.drop_constraint(
        op.f("webhook_subscriptions_org_id_fkey"), "webhook_subscriptions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("webhook_subscriptions_created_by_fkey"), "webhook_subscriptions", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("webhook_subscriptions_created_by_fkey"),
        "webhook_subscriptions",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("webhook_subscriptions_org_id_fkey"),
        "webhook_subscriptions",
        "organizations",
        ["org_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_webhook_subscriptions_org_id"), "webhook_subscriptions", ["org_id"], unique=False
    )
    op.create_foreign_key(
        op.f("webhook_deliveries_subscription_id_fkey"),
        "webhook_deliveries",
        "webhook_subscriptions",
        ["subscription_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_webhook_deliveries_subscription_id"),
        "webhook_deliveries",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_deliveries_status_retry"),
        "webhook_deliveries",
        ["status", "next_retry_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_deliveries_status"), "webhook_deliveries", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_org_id"), "webhook_deliveries", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_next_retry_at"),
        "webhook_deliveries",
        ["next_retry_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_watchlist_alerts_user_id"), table_name="watchlist_alerts")
    op.create_index(
        op.f("ix_waitlist_entries_status"), "waitlist_entries", ["status"], unique=False
    )
    op.create_index(op.f("ix_waitlist_entries_email"), "waitlist_entries", ["email"], unique=False)
    op.create_index(
        op.f("ix_usage_events_org_type_time"),
        "usage_events",
        ["org_id", "event_type", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usage_events_event_type"), "usage_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_usage_events_created_at"), "usage_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_signal_scores_project_time"),
        "signal_scores",
        ["project_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "risk_mitigation_statuses",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("redaction_jobs_org_id_fkey"),
        "redaction_jobs",
        "organizations",
        ["org_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("redaction_jobs_created_by_fkey"),
        "redaction_jobs",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(op.f("ix_redaction_jobs_org_id"), "redaction_jobs", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_redaction_jobs_document_id"), "redaction_jobs", ["document_id"], unique=False
    )
    op.drop_column("prompt_templates", "is_deleted")
    op.add_column(
        "projects",
        sa.Column(
            "project_currency",
            sa.VARCHAR(length=3),
            server_default=sa.text("'EUR'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_org_api_keys_org_id"),
        "org_api_keys",
        "organizations",
        ["org_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("market_enrichment_fetch_logs", "is_deleted")
    op.drop_column("market_data_sources", "is_deleted")
    op.drop_column("market_data_raw", "is_deleted")
    op.drop_column("market_data_processed", "is_deleted")
    op.add_column(
        "investor_risk_profiles",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(
        op.f("ix_investor_readiness_certifications_project_id"),
        table_name="investor_readiness_certifications",
    )
    op.create_index(
        op.f("ix_certification_project"),
        "investor_readiness_certifications",
        ["project_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_industry_taxonomy_parent_code"), table_name="industry_taxonomy")
    op.create_index(
        op.f("ix_taxonomy_parent_code"), "industry_taxonomy", ["parent_code"], unique=False
    )
    op.alter_column(
        "industry_taxonomy", "updated_at", nullable=True, existing_server_default=sa.text("now()")
    )
    op.alter_column(
        "industry_taxonomy", "created_at", nullable=True, existing_server_default=sa.text("now()")
    )
    op.drop_index(op.f("ix_financial_templates_taxonomy_code"), table_name="financial_templates")
    op.create_index(
        op.f("ix_financial_templates_taxonomy"),
        "financial_templates",
        ["taxonomy_code"],
        unique=False,
    )
    op.alter_column(
        "financial_templates", "updated_at", nullable=True, existing_server_default=sa.text("now()")
    )
    op.alter_column(
        "financial_templates", "created_at", nullable=True, existing_server_default=sa.text("now()")
    )
    op.create_index(op.f("ix_feature_flags_name"), "feature_flags", ["name"], unique=False)
    op.create_index(
        op.f("ix_feature_flag_overrides_org_id"), "feature_flag_overrides", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_feature_flag_overrides_flag_name"),
        "feature_flag_overrides",
        ["flag_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_esg_metrics_org_period"), "esg_metrics", ["org_id", "period"], unique=False
    )
    op.create_foreign_key(
        op.f("document_annotations_org_id_fkey"),
        "document_annotations",
        "organizations",
        ["org_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("document_annotations_created_by_fkey"),
        "document_annotations",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_document_annotations_org_id"), "document_annotations", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_annotations_document_id"),
        "document_annotations",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_annotations_created_by"),
        "document_annotations",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_doc_access_logs_doc_time"),
        "document_access_logs",
        ["document_id", "timestamp"],
        unique=False,
    )
    op.drop_index(op.f("ix_digest_logs_org_id"), table_name="digest_logs")
    op.drop_index(op.f("ix_deal_stage_transitions_project_id"), table_name="deal_stage_transitions")
    op.drop_index(op.f("ix_deal_stage_transitions_org_id"), table_name="deal_stage_transitions")
    op.drop_index(op.f("ix_deal_room_members_room_id"), table_name="deal_room_members")
    op.drop_index(op.f("ix_deal_room_activities_room_id"), table_name="deal_room_activities")
    op.drop_column("data_review_queue", "is_deleted")
    op.create_foreign_key(
        op.f("custom_domains_org_id_fkey"),
        "custom_domains",
        "organizations",
        ["org_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_comparable_transactions_close_year"),
        "comparable_transactions",
        ["close_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comparable_transactions_asset_type"),
        "comparable_transactions",
        ["asset_type"],
        unique=False,
    )
    op.drop_index(op.f("ix_blockchain_anchors_tx_hash"), table_name="blockchain_anchors")
    op.drop_index(op.f("ix_blockchain_anchors_event_type"), table_name="blockchain_anchors")
    op.drop_index(op.f("ix_blockchain_anchors_batch_id"), table_name="blockchain_anchors")
    op.create_index(op.f("ix_anchor_tx_hash"), "blockchain_anchors", ["tx_hash"], unique=False)
    op.create_index(
        op.f("ix_anchor_event_type"), "blockchain_anchors", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_anchor_batch_id"), "blockchain_anchors", ["batch_id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_org_time"), "audit_logs", ["org_id", "timestamp"], unique=False
    )
    op.add_column(
        "ai_task_logs",
        sa.Column("processing_time_ms", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ai_task_logs",
        sa.Column("prompt_version", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ai_task_logs",
        sa.Column(
            "validation_repairs",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ai_task_logs",
        sa.Column("confidence_level", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ai_task_logs",
        sa.Column("prompt_template_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ai_task_logs",
        sa.Column(
            "validation_warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ai_task_logs",
        sa.Column(
            "confidence", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("fk_ai_task_logs_prompt_template"),
        "ai_task_logs",
        "prompt_templates",
        ["prompt_template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_ai_task_logs_org_status_time"),
        "ai_task_logs",
        ["org_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_task_logs_confidence_level"), "ai_task_logs", ["confidence_level"], unique=False
    )
    op.create_index(
        op.f("ix_ai_task_logs_confidence"), "ai_task_logs", ["confidence"], unique=False
    )
    op.add_column(
        "ai_output_feedback",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
