"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ComplianceDeadline {
  id: string;
  category: string;
  title: string;
  description: string | null;
  jurisdiction: string | null;
  regulatory_body: string | null;
  due_date: string;
  recurrence: string | null;
  status: string;
  priority: string;
  days_until_due: number;
  is_overdue: boolean;
}

export interface CreateDeadlineBody {
  category: string;
  title: string;
  description?: string;
  jurisdiction?: string;
  regulatory_body?: string;
  due_date: string;
  priority: string;
  recurrence?: string | null;
}

// ── Hooks ─────────────────────────────────────────────────────────────────────

export interface ComplianceResponse {
  items: ComplianceDeadline[];
  overdue_count: number;
  due_this_week: number;
  due_this_month: number;
}

export function useComplianceDeadlines(statusFilter?: string | null) {
  return useQuery<ComplianceResponse>({
    queryKey: ["compliance-deadlines", statusFilter ?? null],
    queryFn: () =>
      api
        .get(`/compliance/deadlines${statusFilter ? `?status=${statusFilter}` : ""}`)
        .then((r) => r.data),
  });
}

export function useAutoGenerateDeadlines() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (body: Record<string, unknown>) =>
      api.post("/compliance/deadlines/auto-generate", body).then((r) => r.data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["compliance-deadlines"] }),
  });
}

export function useCreateDeadline() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (body: Record<string, unknown>) =>
      api.post("/compliance/deadlines", body).then((r) => r.data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["compliance-deadlines"] }),
  });
}

export function useCompleteDeadline() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) =>
      api.post(`/compliance/deadlines/${id}/complete`).then((r) => r.data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["compliance-deadlines"] }),
  });
}

export function useSnoozeDeadline() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, days }: { id: string; days: number }) =>
      api.post(`/compliance/deadlines/${id}/snooze`, { days }).then((r) => r.data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["compliance-deadlines"] }),
  });
}

// ── Helpers ───────────────────────────────────────────────────────────────────

export const CATEGORY_LABELS: Record<string, string> = {
  regulatory_filing: "Regulatory Filing",
  tax: "Tax",
  environmental: "Environmental",
  permit: "Permit",
  license: "License",
  insurance: "Insurance",
  reporting: "Reporting",
  sfdr: "SFDR",
};

export const STATUS_BADGE: Record<string, string> = {
  upcoming: "bg-blue-100 text-blue-700",
  in_progress: "bg-yellow-100 text-yellow-700",
  completed: "bg-green-100 text-green-700",
  overdue: "bg-red-100 text-red-700",
  waived: "bg-gray-100 text-gray-500",
};

export const PRIORITY_DOT: Record<string, string> = {
  critical: "bg-red-500",
  high: "bg-orange-500",
  medium: "bg-yellow-500",
  low: "bg-blue-400",
};
